### ISSUE TITLE
Thumbnails in collection page are not aligned due to missing empty states

### ISSUE THREAD

**Issue by areox-net** [ogptoolbox/ogptoolbox-ui#12]
Should use the same view of Homepage
![screen shot 2016-12-12 at 11 37 57](https://cloud.githubusercontent.com/assets/1255251/21096340/d6da84bc-c05f-11e6-89e0-c5861d6eec81.png)

**Comment by eraviart** [comment]
Corrected, see: https://dev.ogptoolbox.org/fr/collections/14
